<?php

/**
 * Composer Project
 *
 * @author Attila Németh
 * @date 01.12.2020
 */

/**
 * Implements hook_theme()
 */
function packages_theme()
{
  $hooks = [
    //Composer Package
    'composer_package' => [
      'render element' => 'elements',
      'template' => 'composer-package',
      'path' => drupal_get_path('module', 'packages') . '/theme',
    ],
    //Composer Project
    'composer_project' => [
      'render element' => 'elements',
      'template' => 'composer-project',
      'path' => drupal_get_path('module', 'packages') . '/theme',
    ],
  ];
  return $hooks;
}

function template_preprocess_composer_project(&$variables): void
{
  $variables['content'] = $variables['elements'];
  $variables['attributes']['class'][] = 'composer-project';
  $variables['attributes']['class'][] = 'composer-project-' . $variables['elements']['#view_mode'];
}

/**
 * Implements hook_locale_translation_projects_alter()
 */
function packages_locale_translation_projects_alter(&$projects)
{
  $projects['packages'] = [
    'info' => [
      'interface translation project' => 'packages',
      'interface translation server pattern' => drupal_get_path('module', 'packages') . 
          '/translations/packages.%language.po',
    ],
  ];
}

function template_preprocess_composer_package(&$variables): void
{
  $variables['content'] = $variables['elements'];
  $version = $variables['elements']['#composer_package']->get('version')->first()->get('value')->getValue();
  $composer = $variables['elements']['#composer_package']->getComposer();
  $matches = [];
  if (preg_match('/\-(alpha|beta|dev)$/', $version)) {
    $version_string = $version;
  }
  elseif(preg_match('/^([0-9]+)\.([0-9]+)/', $version, $matches)) {
    if ($matches[2] == '0') {
      $version_string = '^' . $matches[1];
    }
    else {
      $version_string = '^' . $matches[1] . '.' . $matches[2];
    }
  }
  else {
    $version_string = $version;
  }
  $variables['content']['composer_string'] = [
    '#prefix' => '<p class="composer">',
    '#suffix' => '</p>',
    '#markup' => 'composer require ' . $composer['name'] . ':' . $version_string,
    '#weight' => -39,
  ];
}